---
version: "2.1"
services:
  snipe-it:
    image: snipe/snipe-it
    container_name: snipe-it
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - APP_TIMEZONE=${TZ}
      - APP_URL=https://cmdb.finchtech.com
      - MYSQL_PORT_3306_TCP_ADDR=db
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=${MYSQLSA}
      - MYSQL_PASSWORD=${MYSQLSA}
      - MAIL_PORT_587_TCP_ADDR=mailserver
      - MAIL_PORT_587_TCP_PORT=587
      - MAIL_ENV_FROM_ADDR=allen@finchtech.com
      - MAIL_ENV_FROM_NAME=FinchTech
      - MAIL_ENV_ENCRYPTION=tcp
      - MAIL_ENV_USERNAME=messenger@finchtech.com
      - MAIL_ENV_PASSWORD=${MSGPASSWORD}
      - APP_ENV=production
      - APP_DEBUG=true
      - APP_KEY=${APPKEY}
      - APP_LOCALE=en
      - PHP_UPLOAD_LIMIT=100
      - APP_TRUSTED_PROXIES=REMOTE_ADDR
      - SECURE_COOKIES=true
    volumes:
      - ${LOCVOL1}snipe-it:/var/lib/snipeit
    #ports:
    #  - 80:80
    #  - 443:443
    restart: unless-stopped
    depends_on:
    - db
#
  db:
    image: mysql:5.6
    container_name: snipe-it-db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - APP_TIMEZONE=${TZ}
      - APP_URL=https://cmdb.finchtech.com
      - MYSQL_PORT_3306_TCP_ADDR=db
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=${MYSQLSA}
      - MYSQL_PASSWORD=${MYSQLSA}
      - MAIL_PORT_587_TCP_ADDR=mailserver
      - MAIL_PORT_587_TCP_PORT=587
      - MAIL_ENV_FROM_ADDR=allen@finchtech.com
      - MAIL_ENV_FROM_NAME=FinchTech
      - MAIL_ENV_ENCRYPTION=tcp
      - MAIL_ENV_USERNAME=messenger@finchtech.com
      - MAIL_ENV_PASSWORD=${MSGPASSWORD}
      - APP_ENV=production
      - APP_DEBUG=true
      - APP_KEY=${APPKEY}
      - APP_LOCALE=en
      - PHP_UPLOAD_LIMIT=100
      - APP_TRUSTED_PROXIES=REMOTE_ADDR
      - SECURE_COOKIES=true
    volumes:
      - ${LOCVOL1}snipe-it-db:/var/lib/mysql
    #ports:
    #  - 80:80
    #  - 443:443
    restart: unless-stopped
#
#
#
networks:
  default:
    external: true
    name: ${CONNET}
