---
version: "2.1"
services:
  snipe-it:
    image: lscr.io/linuxserver/snipe-it:latest
    container_name: snipe-it
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - APP_URL=https://cmdb.finchtech.com
      - MYSQL_PORT_3306_TCP_ADDR=db
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeituser
      - MYSQL_PASSWORD=${MYSQLSA}
      - DOCKER_MODS=linuxserver/mods:swag-imagemagick|linuxserver/mods:universal-cron
      - MAIL_PORT_587_TCP_ADDR=mailserver
      - MAIL_PORT_587_TCP_PORT=25
      - MAIL_ENV_FROM_ADDR=allen@finchtech.com
      - MAIL_ENV_FROM_NAME=allen@finchtech.com
      - MAIL_ENV_ENCRYPTION=tcp
      - MAIL_ENV_USERNAME=messenger@finchtech.com
      - MAIL_ENV_PASSWORD=${MSGPASSWORD}
    volumes:
      - ${LOCVOL1}snipe-it:/config
    #ports:
    #  - 80:80
    #  - 443:443
    restart: unless-stopped
    depends_on:
    - db
#
  db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: snipe-it-db
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:universal-cron
      - MYSQL_ROOT_PASSWORD=${MYSQLSA}
      - MYSQL_DATABASE=snipeit #optional
      - MYSQL_USER=snipeituser #optional
      - MYSQL_PASSWORD=${MYSQLSA} #optional
    volumes:
      - ${LOCVOL1}snipe-it-db:/config
    #ports:
    #  - 3306:3306
    restart: unless-stopped
#
#
#
networks:
  default:
    external: true
    name: ${CONNET}
